window.MODULES = window.MODULES || [];
window.MODULES.push({
  order: 3,
  title: "3 · Workspaces and packages",
  lessons: [
    {
      id: "3.1", title: "Workspaces and colcon", minutes: 15,
      blocks: [
        ["p", "Until now your nodes were loose scripts. Real ROS 2 projects are organised into <b>packages</b>, and packages live in a <b>workspace</b>. A workspace is just a folder with a standard layout, and <b>colcon</b> is the tool that builds everything inside it."],
        ["h", "Create your workspace"],
        ["cmd", "mkdir -p ~/ros2_ws/src"],
        ["cmd", "cd ~/ros2_ws"],
        ["cmd", "colcon build"],
        ["out", "Summary: 0 packages finished [0.81s]"],
        ["cmd", "ls"],
        ["out", "build  install  log  src"],
        ["p", "There are no packages yet, so nothing was built, but colcon created its folders:"],
        ["ul", [
          "<code>src</code>: <b>your code</b>. The only folder you edit.",
          "<code>build</code>: temporary files made during building.",
          "<code>install</code>: the finished result. This is what ROS 2 actually runs.",
          "<code>log</code>: build logs, handy when a build fails."
        ]],
        ["warn", "Always run <code>colcon build</code> from the <b>workspace root</b> (<code>~/ros2_ws</code>), never from inside <code>src</code>. Building from the wrong folder creates stray <code>build</code> and <code>install</code> folders and confusing errors."],
        ["h", "Underlay and overlay"],
        ["p", "ROS 2 itself, in <code>/opt/ros/humble</code>, is the <b>underlay</b>. Your workspace is an <b>overlay</b> placed on top. After each build you must tell the terminal about your new packages by sourcing the overlay:"],
        ["cmd", "source ~/ros2_ws/install/setup.bash"],
        ["p", "Just like in lesson 0.4, sourcing only affects that one terminal. To avoid doing it by hand every time, add it to your <code>~/.bashrc</code> <b>once</b>:"],
        ["cmd", "echo \"source ~/ros2_ws/install/setup.bash\" >> ~/.bashrc"],
        ["warn", "Run that <code>echo</code> line <b>only once</b>. Running it again adds a duplicate line (harmless, but untidy). Open a new terminal afterwards so the change takes effect."],
        ["note", "The &quot;I built it but ROS 2 cannot find my package&quot; problem is almost always a terminal that was open before the build, or that never sourced the overlay. Lesson 3.7 covers it."],
        ["try", "Create the workspace, run <code>colcon build</code>, and list the folders with <code>ls</code>. Then look inside <code>install</code> with <code>ls install</code>."],
        ["quiz", {
          q: "Which folder in a workspace do you write your own code in?",
          options: ["build", "install", "src", "log"],
          answer: 2,
          why: "Only <code>src</code> holds your source code. <code>build</code>, <code>install</code> and <code>log</code> are generated by colcon and can be deleted and rebuilt."
        }]
      ]
    },
    {
      id: "3.2", title: "Your first package", minutes: 25,
      blocks: [
        ["p", "A <b>package</b> is the unit of ROS 2 software: a folder holding your nodes, their settings and a description of what they depend on. Let us create one for the turtle code."],
        ["cmd", "cd ~/ros2_ws/src"],
        ["cmd", "ros2 pkg create --build-type ament_python --license MIT turtle_tools --dependencies rclpy geometry_msgs turtlesim"],
        ["out", "going to create a new package\npackage name: turtle_tools\ndestination directory: /home/student/ros2_ws/src\npackage format: 3\nversion: 0.0.0\ndescription: TODO: Package description\nmaintainer: ['student <student@todo.todo>']\nlicenses: ['MIT']\nbuild type: ament_python\ndependencies: ['rclpy', 'geometry_msgs', 'turtlesim']\ncreating folder ./turtle_tools\n..."],
        ["ul", [
          "<code>--build-type ament_python</code>: a Python package. (C++ packages use <code>ament_cmake</code>, which you will meet in lesson 3.6.)",
          "<code>--license MIT</code>: a standard open-source licence. Without it you get a warning.",
          "<code>turtle_tools</code>: the package name.",
          "<code>--dependencies ...</code>: other packages this one uses. Our nodes import <code>rclpy</code>, <code>geometry_msgs</code> and <code>turtlesim</code>."
        ]],
        ["h", "What was created"],
        ["cmd", "find turtle_tools -type f | sort"],
        ["out", "turtle_tools/package.xml\nturtle_tools/resource/turtle_tools\nturtle_tools/setup.cfg\nturtle_tools/setup.py\nturtle_tools/test/test_copyright.py\nturtle_tools/test/test_flake8.py\nturtle_tools/test/test_pep257.py\nturtle_tools/turtle_tools/__init__.py"],
        ["ul", [
          "<code>package.xml</code>: the package's <b>ID card</b>: name, version, description, and which other packages it depends on.",
          "<code>setup.py</code>: tells Python how to install it, including the list of <b>executables</b> (nodes) it provides. You will edit this in the next lesson.",
          "<code>turtle_tools/turtle_tools/</code>: the inner folder with the <b>same name</b> is where your Python code goes.",
          "<code>resource/</code> and <code>setup.cfg</code>: bookkeeping files. Leave them alone."
        ]],
        ["p", "The generated description is a placeholder. Fix it with one command:"],
        ["cmd", "sed -i 's|TODO: Package description|Tools for driving the turtle|' turtle_tools/package.xml"],
        ["cmd", "grep description turtle_tools/package.xml"],
        ["out", "  <description>Tools for driving the turtle</description>"],
        ["h", "Check dependencies, then build"],
        ["cmd", "cd ~/ros2_ws"],
        ["cmd", "rosdep install -i --from-path src --rosdistro humble -y"],
        ["out", "#All required rosdeps installed successfully"],
        ["p", "<b>rosdep</b> reads every <code>package.xml</code> in <code>src</code> and installs anything missing. Here everything was already installed. On other projects this step saves you from hunting down missing libraries."],
        ["cmd", "colcon build --packages-select turtle_tools"],
        ["out", "Starting >>> turtle_tools\nFinished <<< turtle_tools [1.84s]\n\nSummary: 1 package finished [2.30s]"],
        ["p", "<code>--packages-select</code> builds only the named package, which is quicker when the workspace gets larger. Now make the terminal see it:"],
        ["cmd", "source install/setup.bash"],
        ["cmd", "ros2 pkg list | grep turtle_tools"],
        ["out", "turtle_tools"],
        ["p", "Your package is registered. <code>ros2 pkg list</code> lists every package ROS 2 can find, and <code>grep</code> filters it to the line you want. It has no nodes yet:"],
        ["cmd", "ros2 pkg executables turtle_tools"],
        ["p", "That printed nothing, because nothing in it can be run yet. Fixing that is the next lesson."],
        ["warn", "Package names must be lowercase, with underscores, and should not match a Python library name. <code>turtle_tools</code> is safe, but a package called <code>math</code> or <code>test</code> would cause trouble."],
        ["try", "Look inside the package with <code>ls turtle_tools</code> and open <code>turtle_tools/package.xml</code> with <code>cat</code>. Find the three <code>&lt;depend&gt;</code> lines."],
        ["quiz", {
          q: "What is <code>package.xml</code> for?",
          options: [
            "It holds your Python code",
            "It describes the package: its name, version, and the other packages it depends on",
            "It is where colcon stores build logs",
            "It starts your nodes"
          ],
          answer: 1,
          why: "It is the package's metadata. rosdep and colcon read it to know what the package needs."
        }]
      ]
    },
    {
      id: "3.3", title: "Put your nodes in the package", minutes: 25,
      blocks: [
        ["p", "Time to move the three nodes you wrote in Module 2 into <code>turtle_tools</code>. Two steps: copy the files into the package, then tell <code>setup.py</code> which ones are runnable programs."],
        ["cmd", "cp ~/ros2_practice/circle_publisher.py ~/ros2_practice/pose_listener.py ~/ros2_practice/wall_avoider.py ~/ros2_ws/src/turtle_tools/turtle_tools/"],
        ["cmd", "ls ~/ros2_ws/src/turtle_tools/turtle_tools/"],
        ["out", "__init__.py  circle_publisher.py  pose_listener.py  wall_avoider.py"],
        ["h", "Declare the executables"],
        ["p", "Python can run any file, but <code>ros2 run</code> only knows about programs listed in <code>setup.py</code> under <code>entry_points</code>. Each line says: <i>command name</i> = <i>module</i>:<i>function</i>. Replace the whole file by pasting this block. Windows Terminal may warn about pasting multiple lines: that is fine, choose to paste."],
        ["cmd", "cat > ~/ros2_ws/src/turtle_tools/setup.py << 'EOF'\nimport os\nfrom glob import glob\n\nfrom setuptools import find_packages, setup\n\npackage_name = 'turtle_tools'\n\nsetup(\n    name=package_name,\n    version='0.0.1',\n    packages=find_packages(exclude=['test']),\n    data_files=[\n        ('share/ament_index/resource_index/packages',\n            ['resource/' + package_name]),\n        ('share/' + package_name, ['package.xml']),\n        (os.path.join('share', package_name, 'launch'), glob('launch/*.launch.py')),\n    ],\n    install_requires=['setuptools'],\n    zip_safe=True,\n    maintainer='ROS learner',\n    maintainer_email='you@example.com',\n    description='Tools for driving the turtle',\n    license='MIT',\n    extras_require={\n        'test': ['pytest'],\n    },\n    entry_points={\n        'console_scripts': [\n            'circle_publisher = turtle_tools.circle_publisher:main',\n            'pose_listener = turtle_tools.pose_listener:main',\n            'wall_avoider = turtle_tools.wall_avoider:main',\n        ],\n    },\n)\nEOF", "Ubuntu terminal · paste the whole block"],
        ["p", "The <code>entry_points</code> part is what matters:"],
        ["ul", [
          "<code>'wall_avoider = turtle_tools.wall_avoider:main'</code> means: make a command called <code>wall_avoider</code> that runs the <code>main</code> function in the file <code>turtle_tools/wall_avoider.py</code>. That is why every node has a <code>main()</code> function (lesson 1.8).",
          "The <code>glob('launch/*.launch.py')</code> line prepares for launch files in lesson 3.4. It does nothing yet."
        ]],
        ["h", "Build with --symlink-install"],
        ["cmd", "cd ~/ros2_ws"],
        ["cmd", "colcon build --packages-select turtle_tools --symlink-install"],
        ["out", "Starting >>> turtle_tools\nFinished <<< turtle_tools [3.29s]\n\nSummary: 1 package finished [3.90s]"],
        ["cmd", "source install/setup.bash"],
        ["cmd", "ros2 pkg executables turtle_tools"],
        ["out", "turtle_tools circle_publisher\nturtle_tools pose_listener\nturtle_tools wall_avoider"],
        ["p", "Your three nodes are now registered. <code>--symlink-install</code> links the installed files back to your source files, so from now on <b>edits to your Python code take effect immediately</b>, without rebuilding. You only rebuild when you add new files or change <code>setup.py</code> or <code>package.xml</code>."],
        ["h", "Run it like a real ROS 2 package"],
        ["p", "Terminal 1, the simulator:"],
        ["cmd", "ros2 run turtlesim turtlesim_node", "Ubuntu terminal 1"],
        ["p", "Terminal 2, your node, started by package name and command name:"],
        ["cmd", "ros2 run turtle_tools wall_avoider", "Ubuntu terminal 2"],
        ["out", "[INFO] [...] [wall_avoider]: Wall ahead, turning\n[INFO] [...] [wall_avoider]: Clear, driving straight\n..."],
        ["p", "The turtle wanders as before, but now you launched it with <code>ros2 run &lt;package&gt; &lt;executable&gt;</code>, exactly like turtlesim's own nodes. Stop it with Ctrl+C."],
        ["note", "You no longer need to be in a particular folder or type <code>python3 file.py</code>. ROS 2 finds the package from anywhere, as long as the terminal has sourced your workspace."],
        ["try", "Run <code>circle_publisher</code> and <code>pose_listener</code> the same way (<code>ros2 run turtle_tools circle_publisher</code>). Then change the speed in <code>~/ros2_ws/src/turtle_tools/turtle_tools/circle_publisher.py</code>, save, and run it again <i>without rebuilding</i>."],
        ["quiz", {
          q: "You add a <b>new</b> node file and a new line in <code>entry_points</code>. What must you do before <code>ros2 run</code> can find it?",
          options: [
            "Nothing, it works instantly",
            "Rebuild with colcon and source the workspace again",
            "Reinstall ROS 2",
            "Restart Windows"
          ],
          answer: 1,
          why: "Changing <code>setup.py</code> needs a rebuild. Symlink install only spares you the rebuild when you edit the contents of a file that is already registered."
        }]
      ]
    },
    {
      id: "3.4", title: "Launch files", minutes: 25,
      blocks: [
        ["p", "Running a simulation took two terminals: one for turtlesim, one for your node. Real robots have dozens of nodes. A <b>launch file</b> starts a whole group of nodes with one command. It is written in Python."],
        ["cmd", "mkdir -p ~/ros2_ws/src/turtle_tools/launch"],
        ["cmd", "cat > ~/ros2_ws/src/turtle_tools/launch/avoid.launch.py << 'EOF'\nfrom launch import LaunchDescription\nfrom launch_ros.actions import Node\n\n\ndef generate_launch_description():\n    return LaunchDescription([\n        Node(package=\"turtlesim\", executable=\"turtlesim_node\"),\n        Node(package=\"turtle_tools\", executable=\"wall_avoider\", output=\"screen\"),\n    ])\nEOF", "Ubuntu terminal · paste the whole block"],
        ["ul", [
          "The function must be called <code>generate_launch_description</code>. ROS 2 looks for that name.",
          "It returns a <code>LaunchDescription</code>: a list of things to start.",
          "Each <code>Node(package=..., executable=...)</code> is one node, using the same names as <code>ros2 run &lt;package&gt; &lt;executable&gt;</code>.",
          "<code>output=\"screen\"</code> prints that node's log messages in your terminal."
        ]],
        ["p", "The <code>setup.py</code> you wrote in lesson 3.3 already installs everything in the <code>launch</code> folder, but because this file is <b>new</b>, rebuild:"],
        ["cmd", "cd ~/ros2_ws"],
        ["cmd", "colcon build --packages-select turtle_tools --symlink-install"],
        ["cmd", "source install/setup.bash"],
        ["p", "Make sure no other turtlesim or avoider is still running, then launch everything with one command:"],
        ["cmd", "ros2 launch turtle_tools avoid.launch.py"],
        ["out", "[INFO] [launch]: All log files can be found below /home/student/.ros/log/...\n[INFO] [launch]: Default logging verbosity is set to INFO\n[INFO] [turtlesim_node-1]: process started with pid [16024]\n[INFO] [wall_avoider-2]: process started with pid [16026]\n[turtlesim_node-1] [INFO] [...] [turtlesim]: Starting turtlesim with node name /turtlesim\n[turtlesim_node-1] [INFO] [...] [turtlesim]: Spawning turtle [turtle1] at x=[5.544445], y=[5.544445], theta=[0.000000]\n[wall_avoider-2] [INFO] [...] [wall_avoider]: Wall ahead, turning\n..."],
        ["p", "The turtlesim window opens and the turtle starts wandering, from <b>one</b> command in <b>one</b> terminal. Each log line is tagged with the node that printed it, like <code>[wall_avoider-2]</code>."],
        ["p", "While it runs, open another terminal and check:"],
        ["cmd", "ros2 node list", "Ubuntu terminal 2"],
        ["out", "/turtlesim\n/wall_avoider"],
        ["p", "Press <b>Ctrl+C</b> in the launch terminal. Both programs stop together, which is the other big convenience of launch files."],
        ["note", "Launch files can do much more: start nodes in different <b>namespaces</b>, <b>rename</b> topics, set parameters (next lesson) and include other launch files. Even large robots like the TurtleBot start with one launch command."],
        ["try", "Add a third node to the launch file: <code>Node(package=\"turtle_tools\", executable=\"pose_listener\", output=\"screen\")</code>. Rebuild is not needed for edits to an already-installed launch file, because you used <code>--symlink-install</code>. Launch again and watch the position lines appear."],
        ["quiz", {
          q: "What is the main benefit of a launch file?",
          options: [
            "It makes the nodes run faster",
            "It starts and stops a whole group of nodes with a single command",
            "It replaces <code>package.xml</code>",
            "It is required for any ROS 2 node to work"
          ],
          answer: 1,
          why: "Launch files do not change how nodes work. They just save you from opening a terminal per node."
        }]
      ]
    },
    {
      id: "3.5", title: "Parameters in your own node", minutes: 25,
      blocks: [
        ["p", "In lesson 2.5 you changed turtlesim's settings while it ran. Your own nodes can have parameters too, so you can tune the speed without editing code. Replace <code>wall_avoider.py</code> with a version that has two parameters, <code>speed</code> and <code>turn_speed</code>:"],
        ["cmd", "cat > ~/ros2_ws/src/turtle_tools/turtle_tools/wall_avoider.py << 'EOF'\nimport math\n\nimport rclpy\nfrom rclpy.node import Node\nfrom geometry_msgs.msg import Twist\nfrom turtlesim.msg import Pose\n\n\nclass WallAvoider(Node):\n    def __init__(self):\n        super().__init__(\"wall_avoider\")\n        self.declare_parameter(\"speed\", 2.0)\n        self.declare_parameter(\"turn_speed\", 2.0)\n        self.publisher = self.create_publisher(Twist, \"/turtle1/cmd_vel\", 10)\n        self.subscription = self.create_subscription(Pose, \"/turtle1/pose\", self.on_pose, 10)\n        self.turning = False\n\n    def on_pose(self, msg):\n        speed = self.get_parameter(\"speed\").value\n        turn_speed = self.get_parameter(\"turn_speed\").value\n\n        # The point 1 metre in front of the turtle, in the direction it is facing\n        ahead_x = msg.x + math.cos(msg.theta)\n        ahead_y = msg.y + math.sin(msg.theta)\n        wall_ahead = not (0.5 < ahead_x < 10.5 and 0.5 < ahead_y < 10.5)\n\n        cmd = Twist()\n        if wall_ahead:\n            cmd.angular.z = turn_speed\n        else:\n            cmd.linear.x = speed\n\n        if wall_ahead != self.turning:\n            self.turning = wall_ahead\n            self.get_logger().info(\"Wall ahead, turning\" if wall_ahead else \"Clear, driving straight\")\n\n        self.publisher.publish(cmd)\n\n\ndef main():\n    rclpy.init()\n    node = WallAvoider()\n    try:\n        rclpy.spin(node)\n    except KeyboardInterrupt:\n        pass\n    finally:\n        node.destroy_node()\n        if rclpy.ok():\n            rclpy.shutdown()\n\n\nif __name__ == \"__main__\":\n    main()\nEOF", "Ubuntu terminal · paste the whole block"],
        ["h", "What changed"],
        ["ul", [
          "<code>self.declare_parameter(\"speed\", 2.0)</code>: &quot;this node has a parameter called <code>speed</code>, default 2.0&quot;. Declaring is required.",
          "<code>self.get_parameter(\"speed\").value</code>: reads the current value. It is read <b>every time</b> the callback runs, so changes take effect immediately.",
          "The two speeds replace the fixed <code>2.0</code> numbers from before."
        ]],
        ["p", "Because of <code>--symlink-install</code> no rebuild is needed. Start the simulator in terminal 1 (<code>ros2 run turtlesim turtlesim_node</code>), then in terminal 2 set a parameter <b>on the command line</b> with <code>--ros-args -p</code>:"],
        ["cmd", "ros2 run turtle_tools wall_avoider --ros-args -p speed:=3.0", "Ubuntu terminal 2"],
        ["p", "The turtle now moves faster. In terminal 3, inspect and change it while it runs, using the tools from lesson 2.5:"],
        ["cmd", "ros2 param list /wall_avoider", "Ubuntu terminal 3"],
        ["out", "  speed\n  turn_speed\n  use_sim_time"],
        ["cmd", "ros2 param get /wall_avoider speed"],
        ["out", "Double value is: 3.0"],
        ["cmd", "ros2 param set /wall_avoider speed 1.0"],
        ["out", "Set parameter successful"],
        ["p", "The turtle slows down at once, without restarting anything. <code>use_sim_time</code> is a standard parameter every node gets, which you can ignore for now."],
        ["h", "Set parameters from a launch file"],
        ["p", "Usually you set parameters in a launch file. Add a second one with faster settings:"],
        ["cmd", "cat > ~/ros2_ws/src/turtle_tools/launch/avoid_fast.launch.py << 'EOF'\nfrom launch import LaunchDescription\nfrom launch_ros.actions import Node\n\n\ndef generate_launch_description():\n    return LaunchDescription([\n        Node(package=\"turtlesim\", executable=\"turtlesim_node\"),\n        Node(\n            package=\"turtle_tools\",\n            executable=\"wall_avoider\",\n            output=\"screen\",\n            parameters=[{\"speed\": 4.0, \"turn_speed\": 3.0}],\n        ),\n    ])\nEOF", "Ubuntu terminal · paste the whole block"],
        ["p", "It is a new file, so rebuild, source, and launch it (stop any other turtlesim first):"],
        ["cmd", "cd ~/ros2_ws && colcon build --packages-select turtle_tools --symlink-install && source install/setup.bash"],
        ["cmd", "ros2 launch turtle_tools avoid_fast.launch.py"],
        ["p", "The turtle moves noticeably faster. You can confirm the values from another terminal with <code>ros2 param get /wall_avoider speed</code> (4.0) and <code>... turn_speed</code> (3.0)."],
        ["try", "Experiment: what is the smallest <code>speed</code> at which the turtle still gets around the window? Use <code>ros2 param set</code> live to find out. Then make a third launch file called <code>avoid_slow.launch.py</code>."],
        ["quiz", {
          q: "Why can <code>ros2 param set /wall_avoider speed 1.0</code> change the turtle's speed instantly?",
          options: [
            "ROS 2 rewrites the Python file",
            "The node reads the parameter on every callback, so it picks up the new value",
            "The simulator reads it directly",
            "It does not, you must restart the node"
          ],
          answer: 1,
          why: "The code calls <code>get_parameter(\"speed\")</code> each time. If it read the value only once at startup, a live change would be ignored."
        }]
      ]
    },
    {
      id: "3.6", title: "Custom messages", minutes: 35,
      blocks: [
        ["p", "So far you used messages that ROS 2 provides, like <code>Twist</code> and <code>Pose</code>. When none fits, you define your own. We will make <code>TurtleStatus</code> and have the wall avoider publish it."],
        ["note", "Custom messages are the one place a <b>Python</b> package is not enough. They need a separate <b>C++-style (ament_cmake)</b> package, because ROS 2 generates code from your definition. You do not write any C++. You just fill in two files. This is the longest lesson, so take it step by step."],
        ["h", "1. Create the interface package"],
        ["cmd", "cd ~/ros2_ws/src"],
        ["cmd", "ros2 pkg create --build-type ament_cmake --license MIT turtle_interfaces"],
        ["cmd", "mkdir -p turtle_interfaces/msg"],
        ["h", "2. Define the message"],
        ["p", "A message file lists a <b>type</b> and a <b>name</b> per line. The file name must start with a capital letter."],
        ["cmd", "cat > turtle_interfaces/msg/TurtleStatus.msg << 'EOF'\nfloat32 x\nfloat32 y\nbool near_wall\nstring state\nEOF", "Ubuntu terminal · paste the whole block"],
        ["h", "3. Tell the build system about it"],
        ["p", "Replace the generated <code>CMakeLists.txt</code> (the build recipe) and <code>package.xml</code> with these. The key lines are <code>rosidl_generate_interfaces</code>, which turns the <code>.msg</code> file into usable code, and the <code>rosidl</code> entries in <code>package.xml</code>."],
        ["cmd", "cat > turtle_interfaces/CMakeLists.txt << 'EOF'\ncmake_minimum_required(VERSION 3.8)\nproject(turtle_interfaces)\n\nfind_package(ament_cmake REQUIRED)\nfind_package(rosidl_default_generators REQUIRED)\n\nrosidl_generate_interfaces(${PROJECT_NAME}\n  \"msg/TurtleStatus.msg\"\n)\n\nament_package()\nEOF", "Ubuntu terminal · paste the whole block"],
        ["cmd", "cat > turtle_interfaces/package.xml << 'EOF'\n<?xml version=\"1.0\"?>\n<?xml-model href=\"http://download.ros.org/schema/package_format3.xsd\" schematypens=\"http://www.w3.org/2001/XMLSchema\"?>\n<package format=\"3\">\n  <name>turtle_interfaces</name>\n  <version>0.0.1</version>\n  <description>Custom messages for the turtle</description>\n  <maintainer email=\"you@example.com\">ROS learner</maintainer>\n  <license>MIT</license>\n\n  <buildtool_depend>ament_cmake</buildtool_depend>\n  <buildtool_depend>rosidl_default_generators</buildtool_depend>\n\n  <exec_depend>rosidl_default_runtime</exec_depend>\n  <member_of_group>rosidl_interface_packages</member_of_group>\n\n  <export>\n    <build_type>ament_cmake</build_type>\n  </export>\n</package>\nEOF", "Ubuntu terminal · paste the whole block"],
        ["h", "4. Make turtle_tools depend on it"],
        ["cmd", "sed -i 's|  <depend>turtlesim</depend>|  <depend>turtlesim</depend>\\n  <depend>turtle_interfaces</depend>|' turtle_tools/package.xml"],
        ["cmd", "grep depend turtle_tools/package.xml | head -6"],
        ["out", "  <depend>rclpy</depend>\n  <depend>geometry_msgs</depend>\n  <depend>turtlesim</depend>\n  <depend>turtle_interfaces</depend>\n  <test_depend>ament_copyright</test_depend>\n  <test_depend>ament_flake8</test_depend>"],
        ["h", "5. Build everything"],
        ["cmd", "cd ~/ros2_ws"],
        ["cmd", "colcon build --symlink-install"],
        ["out", "Starting >>> turtle_interfaces\nFinished <<< turtle_interfaces [29.1s]\nStarting >>> turtle_tools\nFinished <<< turtle_tools [4.96s]\n\nSummary: 2 packages finished [34.7s]"],
        ["p", "The interface package takes about half a minute the first time because code is being generated. colcon builds <code>turtle_interfaces</code> first, since <code>turtle_tools</code> now depends on it. Source and inspect your new message:"],
        ["cmd", "source install/setup.bash"],
        ["cmd", "ros2 interface show turtle_interfaces/msg/TurtleStatus"],
        ["out", "float32 x\nfloat32 y\nbool near_wall\nstring state"],
        ["cmd", "ros2 interface list | grep turtle_interfaces"],
        ["out", "    turtle_interfaces/msg/TurtleStatus"],
        ["p", "ROS 2 now treats <code>TurtleStatus</code> like any built-in message. Use it in the node: this version publishes a status message alongside its drive commands."],
        ["cmd", "cat > ~/ros2_ws/src/turtle_tools/turtle_tools/wall_avoider.py << 'EOF'\nimport math\n\nimport rclpy\nfrom rclpy.node import Node\nfrom geometry_msgs.msg import Twist\nfrom turtlesim.msg import Pose\nfrom turtle_interfaces.msg import TurtleStatus\n\n\nclass WallAvoider(Node):\n    def __init__(self):\n        super().__init__(\"wall_avoider\")\n        self.declare_parameter(\"speed\", 2.0)\n        self.declare_parameter(\"turn_speed\", 2.0)\n        self.publisher = self.create_publisher(Twist, \"/turtle1/cmd_vel\", 10)\n        self.status_publisher = self.create_publisher(TurtleStatus, \"~/status\", 10)\n        self.subscription = self.create_subscription(Pose, \"/turtle1/pose\", self.on_pose, 10)\n        self.turning = False\n\n    def on_pose(self, msg):\n        speed = self.get_parameter(\"speed\").value\n        turn_speed = self.get_parameter(\"turn_speed\").value\n\n        # The point 1 metre in front of the turtle, in the direction it is facing\n        ahead_x = msg.x + math.cos(msg.theta)\n        ahead_y = msg.y + math.sin(msg.theta)\n        wall_ahead = not (0.5 < ahead_x < 10.5 and 0.5 < ahead_y < 10.5)\n\n        cmd = Twist()\n        if wall_ahead:\n            cmd.angular.z = turn_speed\n        else:\n            cmd.linear.x = speed\n\n        if wall_ahead != self.turning:\n            self.turning = wall_ahead\n            self.get_logger().info(\"Wall ahead, turning\" if wall_ahead else \"Clear, driving straight\")\n\n        status = TurtleStatus()\n        status.x = msg.x\n        status.y = msg.y\n        status.near_wall = wall_ahead\n        status.state = \"turning\" if wall_ahead else \"driving\"\n\n        self.publisher.publish(cmd)\n        self.status_publisher.publish(status)\n\n\ndef main():\n    rclpy.init()\n    node = WallAvoider()\n    try:\n        rclpy.spin(node)\n    except KeyboardInterrupt:\n        pass\n    finally:\n        node.destroy_node()\n        if rclpy.ok():\n            rclpy.shutdown()\n\n\nif __name__ == \"__main__\":\n    main()\nEOF", "Ubuntu terminal · paste the whole block"],
        ["ul", [
          "<code>from turtle_interfaces.msg import TurtleStatus</code>: the same <code>from &lt;package&gt;.msg import &lt;Type&gt;</code> pattern as for built-in messages.",
          "<code>\"~/status\"</code>: a topic name starting with <code>~/</code> is <b>private to the node</b>, so it becomes <code>/wall_avoider/status</code>.",
          "You fill in the fields (<code>status.x</code>, <code>status.state</code>, ...) just like a <code>Twist</code>."
        ]],
        ["p", "Run the simulator (terminal 1) and the node (terminal 2: <code>ros2 run turtle_tools wall_avoider</code>), then look at the new topic from terminal 3:"],
        ["cmd", "ros2 topic list | grep status", "Ubuntu terminal 3"],
        ["out", "/wall_avoider/status"],
        ["cmd", "ros2 topic info /wall_avoider/status"],
        ["out", "Type: turtle_interfaces/msg/TurtleStatus\nPublisher count: 1\nSubscription count: 0"],
        ["cmd", "ros2 topic echo /wall_avoider/status --once"],
        ["out", "x: 10.323740005493164\ny: 8.786508560180664\nnear_wall: false\nstate: driving\n---"],
        ["p", "Your own message type is flowing on your own topic. (Your numbers will differ.) Any other node could now subscribe to it."],
        ["warn", "Whenever you <b>change a <code>.msg</code> file or the interface package</b>, rebuild everything (<code>colcon build --symlink-install</code>) and source again in <b>every</b> terminal. Old terminals keep using the old version."],
        ["try", "Add a field <code>float32 speed</code> to <code>TurtleStatus.msg</code>, rebuild, and fill it in the node from the <code>speed</code> parameter. Check it with <code>ros2 interface show</code> and <code>ros2 topic echo</code>."],
        ["quiz", {
          q: "Why does a custom message need its own <code>ament_cmake</code> package?",
          options: [
            "Python cannot send messages",
            "ROS 2 generates code from the <code>.msg</code> file, and that is done by the CMake-based build",
            "Messages must be written in C++",
            "It is only a naming convention"
          ],
          answer: 1,
          why: "A <code>.msg</code> file is a definition. The build system turns it into Python (and C++) code, which needs the <code>rosidl</code> tools set up in the CMake package."
        }]
      ]
    },
    {
      id: "3.7", title: "When things go wrong", minutes: 25,
      blocks: [
        ["p", "Beginners spend more time on errors than on writing code, and that is normal. Almost all workspace problems are one of five. Here are the real messages, and how to fix each one."],
        ["h", "1. Package 'x' not found"],
        ["out", "Package 'turtle_tools' not found"],
        ["p", "<b>Cause:</b> this terminal has not sourced your workspace. It only knows ROS 2 itself, not your overlay. <b>Fix:</b> run <code>source ~/ros2_ws/install/setup.bash</code>, or open a new terminal if you added it to <code>~/.bashrc</code> (lesson 3.1). A terminal that was open <i>before</i> your first build never learned about the package."],
        ["h", "2. No executable found"],
        ["cmd", "ros2 run turtle_tools wall_avoiderr"],
        ["out", "No executable found"],
        ["p", "<b>Cause:</b> the package exists but has no executable with that name. Either a typo, or the entry is missing from <code>entry_points</code> in <code>setup.py</code>. <b>Fix:</b> list what exists with <code>ros2 pkg executables turtle_tools</code>. If your node is missing, add it to <code>setup.py</code>, rebuild and source."],
        ["h", "3. Typo in the package name"],
        ["cmd", "ros2 run turtle_toolz wall_avoider"],
        ["out", "Package 'turtle_toolz' not found"],
        ["p", "It looks identical to problem 1, so check the spelling first. <code>ros2 pkg list | grep turtle</code> shows the real names."],
        ["h", "4. Where is my package?"],
        ["cmd", "ros2 pkg prefix turtle_tools"],
        ["out", "/home/student/ros2_ws/install/turtle_tools"],
        ["p", "Shows which installed copy ROS 2 is using. If it prints an unexpected location, an old copy is shadowing yours."],
        ["h", "5. Strange build problems: start clean"],
        ["p", "When a build gives errors that make no sense, or old behaviour will not go away, delete the generated folders and rebuild. This is safe because <code>build</code>, <code>install</code> and <code>log</code> are all regenerated, and your code in <code>src</code> is untouched."],
        ["cmd", "cd ~/ros2_ws"],
        ["cmd", "rm -rf build install log"],
        ["cmd", "colcon build --symlink-install"],
        ["out", "...\nStarting >>> turtle_tools\nFinished <<< turtle_tools [4.59s]\n\nSummary: 2 packages finished [28.0s]"],
        ["warn", "Check with <code>pwd</code> that you are in <code>~/ros2_ws</code> before running <code>rm -rf</code>. Never use it anywhere else. After a clean rebuild, every terminal needs <code>source install/setup.bash</code> again: until then the terminal only sees <code>turtlesim</code>, not your <code>turtle_tools</code> or <code>turtle_interfaces</code>."],
        ["h", "A debugging routine"],
        ["ul", [
          "<b>Read the last lines</b> of the error first, as with Python tracebacks.",
          "<b>Did you source?</b> New terminal, or <code>source ~/ros2_ws/install/setup.bash</code>.",
          "<b>Did you rebuild?</b> New files, <code>setup.py</code>, <code>package.xml</code> and <code>.msg</code> changes all need a rebuild.",
          "<b>Is it spelled right?</b> Package, executable and topic names are case-sensitive.",
          "<b>Still stuck?</b> Copy the full command and the full error and paste both to Claude."
        ]],
        ["h", "Module 3 capstone"],
        ["p", "Put the module together. Build a <b>status monitor</b> from scratch:"],
        ["ul", [
          "Add a new node <code>status_monitor.py</code> to <code>turtle_tools</code> that <b>subscribes</b> to <code>/wall_avoider/status</code> (type <code>TurtleStatus</code>).",
          "It counts how many times the turtle switches to <code>turning</code> and logs the count once per second (use <code>throttle_duration_sec</code> from lesson 2.7).",
          "Register it in <code>entry_points</code>, rebuild, source.",
          "Write a launch file <code>monitored.launch.py</code> that starts <b>turtlesim, wall_avoider and status_monitor</b> together."
        ]],
        ["note", "No solution is given on purpose. You have already seen every piece. If you get stuck, paste your code and the error to Claude and ask for a hint, not the answer."],
        ["try", "Do the capstone. When <code>ros2 launch turtle_tools monitored.launch.py</code> runs all three nodes and the count goes up, mark this quest complete."],
        ["quiz", {
          q: "You edited <code>setup.py</code> to add a new executable, but <code>ros2 run</code> says <i>No executable found</i>. What did you most likely forget?",
          options: [
            "To restart Windows",
            "To rebuild with colcon and source the workspace again",
            "To delete the <code>src</code> folder",
            "To rename the package"
          ],
          answer: 1,
          why: "<code>setup.py</code> is read at build time. Until you rebuild, the installed package does not know about the new executable."
        }]
      ]
    }
  ]
});
