window.MODULES = window.MODULES || [];
(function () {
  // Join file lines so the XML can be written without escaping every quote.
  function L() { return Array.prototype.slice.call(arguments).join("\n"); }

  var MYBOT = L(
    '<?xml version="1.0"?>',
    '<robot name="mybot">',
    '  <link name="base_link">',
    '    <visual>',
    '      <geometry><box size="0.4 0.2 0.1"/></geometry>',
    '      <material name="blue"><color rgba="0.2 0.4 0.9 1"/></material>',
    '    </visual>',
    '  </link>',
    '  <link name="head">',
    '    <visual>',
    '      <geometry><sphere radius="0.07"/></geometry>',
    '      <material name="white"><color rgba="1 1 1 1"/></material>',
    '    </visual>',
    '  </link>',
    '  <joint name="head_joint" type="fixed">',
    '    <parent link="base_link"/>',
    '    <child link="head"/>',
    '    <origin xyz="0.1 0 0.12"/>',
    '  </joint>',
    '</robot>'
  );

  var WHEELS = L(
    '  <link name="left_wheel">',
    '    <visual>',
    '      <origin rpy="1.5708 0 0"/>',
    '      <geometry><cylinder radius="0.06" length="0.04"/></geometry>',
    '      <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>',
    '    </visual>',
    '  </link>',
    '  <joint name="left_wheel_joint" type="continuous">',
    '    <parent link="base_link"/>',
    '    <child link="left_wheel"/>',
    '    <origin xyz="-0.1 0.12 -0.02"/>',
    '    <axis xyz="0 1 0"/>',
    '  </joint>',
    '',
    '  <link name="right_wheel">',
    '    <visual>',
    '      <origin rpy="1.5708 0 0"/>',
    '      <geometry><cylinder radius="0.06" length="0.04"/></geometry>',
    '      <material name="black"/>',
    '    </visual>',
    '  </link>',
    '  <joint name="right_wheel_joint" type="continuous">',
    '    <parent link="base_link"/>',
    '    <child link="right_wheel"/>',
    '    <origin xyz="-0.1 -0.12 -0.02"/>',
    '    <axis xyz="0 1 0"/>',
    '  </joint>'
  );

  var XACRO = L(
    '<?xml version="1.0"?>',
    '<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">',
    '  <xacro:property name="wheel_radius" value="0.06"/>',
    '  <xacro:property name="wheel_width" value="0.04"/>',
    '',
    '  <material name="blue"><color rgba="0.2 0.4 0.9 1"/></material>',
    '  <material name="white"><color rgba="1 1 1 1"/></material>',
    '  <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>',
    '',
    '  <link name="base_link">',
    '    <visual>',
    '      <geometry><box size="0.4 0.2 0.1"/></geometry>',
    '      <material name="blue"/>',
    '    </visual>',
    '  </link>',
    '',
    '  <link name="head">',
    '    <visual>',
    '      <geometry><sphere radius="0.07"/></geometry>',
    '      <material name="white"/>',
    '    </visual>',
    '  </link>',
    '  <joint name="head_joint" type="fixed">',
    '    <parent link="base_link"/>',
    '    <child link="head"/>',
    '    <origin xyz="0.1 0 0.12"/>',
    '  </joint>',
    '',
    '  <xacro:macro name="wheel" params="name y">',
    '    <link name="${name}_wheel">',
    '      <visual>',
    '        <origin rpy="${pi/2} 0 0"/>',
    '        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>',
    '        <material name="black"/>',
    '      </visual>',
    '    </link>',
    '    <joint name="${name}_wheel_joint" type="continuous">',
    '      <parent link="base_link"/>',
    '      <child link="${name}_wheel"/>',
    '      <origin xyz="-0.1 ${y} -0.02"/>',
    '      <axis xyz="0 1 0"/>',
    '    </joint>',
    '  </xacro:macro>',
    '',
    '  <xacro:wheel name="left" y="0.12"/>',
    '  <xacro:wheel name="right" y="-0.12"/>',
    '</robot>'
  );

  window.MODULES.push({
    order: 4,
    title: "4 · Robot simulation",
    planned: ["Drive and sense with Python", "Nav2 autonomous navigation", "Capstone: your own goal sender"],
    lessons: [
      {
        id: "4.1", title: "Describing a robot (URDF)", minutes: 20,
        blocks: [
          ["p", "Before ROS 2 can show or simulate a robot, it needs to know what the robot <b>looks like and how it fits together</b>. That description is written in a file format called <b>URDF</b> (Unified Robot Description Format). It is plain XML, so you can read it and edit it in any text editor."],
          ["p", "A URDF has only two kinds of building block:"],
          ["ul", [
            "<b>link</b>: a rigid part of the robot (a body, a wheel, a head).",
            "<b>joint</b>: a connection between <b>two</b> links. It says which one is the <code>parent</code>, which is the <code>child</code>, and how the child may move."
          ]],
          ["p", "Together they form a <b>tree</b>. One link is the root (usually <code>base_link</code>) and every other link hangs off it through a joint."],
          ["note", "Units are always <b>metres</b> and <b>radians</b>. Axes follow the ROS convention: <b>x</b> points forward, <b>y</b> points left, <b>z</b> points up."],
          ["h", "Write your first robot"],
          ["p", "Make a practice folder in your Linux home (not in <code>/mnt/c</code>), then create the file below."],
          ["cmd", "mkdir -p ~/robot_practice"],
          ["cmd", "cd ~/robot_practice"],
          ["cmd", "nano mybot.urdf", "Ubuntu (WSL) terminal. Paste the file, then Ctrl+O, Enter, Ctrl+X"],
          ["code", MYBOT, "mybot.urdf"],
          ["p", "Read it from the top. The robot is named <code>mybot</code>. It has two links: <code>base_link</code>, a blue box 0.4 m long, 0.2 m wide and 0.1 m tall, and <code>head</code>, a white sphere of radius 0.07 m. The <code>head_joint</code> glues the head onto the base. Its <code>origin</code> puts the head 0.1 m forward and 0.12 m up from the base."],
          ["p", "The joint type is <code>fixed</code>, meaning the head never moves relative to the base. You will meet a moving type in the next lesson."],
          ["h", "Check it"],
          ["p", "ROS 2 ships a checker that parses a URDF and prints the tree it found:"],
          ["cmd", "check_urdf mybot.urdf"],
          ["out", "robot name is: mybot\n---------- Successfully Parsed XML ---------------\nroot Link: base_link has 1 child(ren)\n    child(1):  head"],
          ["p", "That reads: the root is <code>base_link</code>, and it has one child, <code>head</code>. This is the tree you described."],
          ["h", "When it goes wrong"],
          ["p", "The checker tells you exactly what is broken. If you misspell a link name in a joint (say <code>hed</code> instead of <code>head</code>) you get:"],
          ["out", "Error:   Failed to build tree: child link [hed] of joint [head_joint] not found\n         at line 252 in ./urdf_parser/src/model.cpp\nERROR: Model Parsing the xml failed"],
          ["p", "And if you forget to close a tag such as <code>&lt;/robot&gt;</code>:"],
          ["out", "Error:   Error reading end tag.\n         at line 100 in ./urdf_parser/src/model.cpp\nERROR: Model Parsing the xml failed"],
          ["note", "The line number in these messages points into the ROS parser's own source code, not into your file. Read the sentence, not the number: it names the joint and the link that are wrong."],
          ["try", "Run <code>check_urdf</code> on your file. Then change <code>head</code> to <code>hed</code> in the joint only, run it again and read the error. Undo the typo."],
          ["quiz", {
            q: "In a URDF, what connects two links together?",
            options: ["A material", "A joint", "A geometry", "Another robot tag"],
            answer: 1,
            why: "A <code>joint</code> names a <code>parent</code> link and a <code>child</code> link and says how the child can move. Links never connect to each other directly."
          }]
        ]
      },
      {
        id: "4.2", title: "Seeing it in RViz and adding wheels", minutes: 25,
        blocks: [
          ["p", "A description you cannot see is hard to trust. <b>RViz</b> is ROS 2's 3D viewer. It draws your robot straight from the URDF, so you can check the shape before you ever simulate it."],
          ["h", "One-time setup for graphics in WSL"],
          ["p", "On some laptops (including this one), the graphics driver that WSL uses crashes when RViz or Gazebo ask it for 3D (the log says <code>D3D12: Removing Device</code>). The fix is to ask for <b>software rendering</b>. It is slower but reliable. Add it to <code>~/.bashrc</code> <b>once</b>:"],
          ["cmd", "echo \"export LIBGL_ALWAYS_SOFTWARE=1\" >> ~/.bashrc"],
          ["warn", "Run that line only once, then <b>open a new terminal</b> so it takes effect. If RViz or Gazebo closes by itself seconds after opening, this is the first thing to check: <code>echo $LIBGL_ALWAYS_SOFTWARE</code> should print <code>1</code>."],
          ["h", "Open your robot"],
          ["p", "The <code>urdf_tutorial</code> package has a ready-made launch file that starts RViz, a state publisher and a slider window. You only give it the path to your file:"],
          ["cmd", "cd ~/robot_practice"],
          ["cmd", "ros2 launch urdf_tutorial display.launch.py model:=$HOME/robot_practice/mybot.urdf"],
          ["p", "Give it about 15 to 20 seconds. An RViz window opens showing a blue box with a white ball on top, and small red, green and blue arrows. Those arrows are <b>coordinate frames</b>, one per link: red is x, green is y, blue is z. You will study them properly later in this module."],
          ["ul", [
            "<b>Left-drag</b> in the 3D view to rotate, <b>middle-drag</b> to slide, <b>scroll</b> to zoom.",
            "In the <b>Displays</b> panel, tick <b>RobotModel</b> and <b>TF</b> on and off to see what each one draws.",
            "Close RViz or press <code>Ctrl+C</code> in the terminal when you are done."
          ]],
          ["h", "Give it wheels"],
          ["p", "A fixed joint cannot spin. A wheel needs a <code>continuous</code> joint, which rotates forever around an axis. Open <code>mybot.urdf</code> again and paste the block below <b>just before</b> the final <code>&lt;/robot&gt;</code> line."],
          ["code", WHEELS, "add to mybot.urdf, before </robot>"],
          ["p", "Three new ideas here:"],
          ["ul", [
            "<code>type=\"continuous\"</code>: the joint spins without limit. The axis <code>0 1 0</code> means &quot;around y&quot;, which is the sideways axis, so the wheel rolls forwards.",
            "<code>rpy=\"1.5708 0 0\"</code>: roll, pitch, yaw in radians. A cylinder stands upright by default, so we roll it by 1.5708 (a quarter turn, about 90 degrees) to lie on its side.",
            "The right wheel reuses <code>&lt;material name=\"black\"/&gt;</code> with no colour. Once a material has been defined, you can refer to it by name."
          ]],
          ["cmd", "check_urdf mybot.urdf"],
          ["out", "robot name is: mybot\n---------- Successfully Parsed XML ---------------\nroot Link: base_link has 3 child(ren)\n    child(1):  head\n    child(2):  left_wheel\n    child(3):  right_wheel"],
          ["p", "Now launch it again. This time a second small window appears with <b>sliders</b>, one for each wheel joint. That window is <code>joint_state_publisher_gui</code>. Dragging a slider publishes a joint angle, and the wheel turns in RViz."],
          ["cmd", "ros2 launch urdf_tutorial display.launch.py model:=$HOME/robot_practice/mybot.urdf"],
          ["note", "The sliders window may open behind RViz. Check the Windows taskbar if you cannot find it."],
          ["try", "Launch the robot with wheels and drag the <code>left_wheel_joint</code> slider. Watch the left wheel turn. Then change the left wheel&apos;s <code>origin</code> y value, run <code>check_urdf</code>, relaunch, and see the wheel move."],
          ["quiz", {
            q: "You want a wheel that can spin around forever. Which joint type do you use?",
            options: ["fixed", "continuous", "static", "floating"],
            answer: 1,
            why: "<code>continuous</code> rotates without limits around its axis. <code>fixed</code> never moves. (There is also <code>revolute</code>, which turns but only between limits, like an elbow.)"
          }]
        ]
      },
      {
        id: "4.3", title: "Less typing with xacro", minutes: 25,
        blocks: [
          ["p", "Look at the two wheels in your URDF. They are almost identical: only the name and one number change. Real robots have dozens of repeated parts, and copy-pasting is how typos get in. <b>xacro</b> (XML macros) fixes this. It is the same XML with three extra features, and a tool turns it into a normal URDF."],
          ["ul", [
            "<b>Properties</b>: named values, like <code>wheel_radius</code>, defined once and used anywhere.",
            "<b>Macros</b>: a reusable block with parameters, like a function.",
            "<b>Maths</b>: <code>${...}</code> expressions, including the constant <code>pi</code>."
          ]],
          ["h", "Your robot as xacro"],
          ["cmd", "nano mybot.xacro", "Ubuntu (WSL) terminal. Paste the file, then Ctrl+O, Enter, Ctrl+X"],
          ["code", XACRO, "mybot.xacro"],
          ["p", "Compare it with the URDF:"],
          ["ul", [
            "The <code>xmlns:xacro</code> part on the first <code>robot</code> line switches the xacro features on. Without it, <code>xacro:</code> tags are an error.",
            "<code>wheel_radius</code> and <code>wheel_width</code> are properties. To make bigger wheels, change <b>one</b> number at the top.",
            "The <code>wheel</code> macro takes a <code>name</code> and a <code>y</code> position. The last two lines <b>use</b> it: one call makes the left wheel, one makes the right.",
            "<code>${name}_wheel</code> pastes the parameter into a name, so you get <code>left_wheel</code> and <code>right_wheel</code>. <code>${pi/2}</code> is a quarter turn, so you no longer type 1.5708.",
            "The materials are defined once at the top, then referred to by name everywhere."
          ]],
          ["h", "Turn it into URDF"],
          ["p", "ROS 2 tools want plain URDF. The <code>xacro</code> command expands your macros and prints the result:"],
          ["cmd", "xacro mybot.xacro > mybot_generated.urdf"],
          ["cmd", "check_urdf mybot_generated.urdf"],
          ["out", "robot name is: mybot\n---------- Successfully Parsed XML ---------------\nroot Link: base_link has 3 child(ren)\n    child(1):  head\n    child(2):  left_wheel\n    child(3):  right_wheel"],
          ["p", "The same tree as your hand-written URDF, from a file that is much shorter to extend. Open <code>mybot_generated.urdf</code> and look at how the macro was expanded into two full wheels."],
          ["note", "You do not have to run <code>xacro</code> yourself to view a robot. The <code>urdf_tutorial</code> launch file accepts a <code>.xacro</code> file directly and expands it for you."],
          ["cmd", "ros2 launch urdf_tutorial display.launch.py model:=$HOME/robot_practice/mybot.xacro"],
          ["p", "You should see the same robot as before: blue body, white head, two black wheels, and sliders for the two wheel joints."],
          ["warn", "Never edit <code>mybot_generated.urdf</code>. It is output. Edit <code>mybot.xacro</code> and regenerate, otherwise your changes vanish the next time you run <code>xacro</code>."],
          ["try", "Change <code>wheel_radius</code> to <code>0.09</code> in <code>mybot.xacro</code>, relaunch with the <code>.xacro</code> file, and see both wheels grow. Then add a third call, <code>&lt;xacro:wheel name=\"spare\" y=\"0.3\"/&gt;</code>, and see a new wheel appear (and a new slider)."],
          ["quiz", {
            q: "You want all four wheels of a robot to be 8 cm in radius, and to change that later in one place. What do you use in xacro?",
            options: [
              "Copy and paste the number four times",
              "A property such as <code>wheel_radius</code>, used with <code>${wheel_radius}</code>",
              "A joint of type fixed",
              "A second URDF file"
            ],
            answer: 1,
            why: "A <code>xacro:property</code> stores the value once, and every <code>${wheel_radius}</code> reads it. Change the property and every wheel changes."
          }]
        ]
      },
      {
        id: "4.4", title: "Coordinate frames (TF2)", minutes: 25,
        blocks: [
          ["p", "In lesson 4.2 you saw little red, green and blue arrows on every part of your robot. Each set of arrows is a <b>coordinate frame</b>: an origin and three axes attached to one link. Robots live and die by frames. A lidar says &quot;obstacle 1 metre ahead&quot;, but ahead of <i>what</i>? The lidar? The robot body? The map? To combine information you must convert between frames."],
          ["p", "<b>TF2</b> is the ROS 2 system that does this. It keeps a <b>tree of frames</b>, the same tree as your URDF links, and can work out the position of any frame relative to any other by walking the tree."],
          ["ul", [
            "<code>/tf</code>: transforms that <b>change</b> over time, such as a spinning wheel.",
            "<code>/tf_static</code>: transforms that <b>never change</b>, such as the head glued to the body. They are sent once and remembered."
          ]],
          ["h", "Publish the frames of your robot"],
          ["p", "In lesson 4.2 the launch file started the helper nodes for you. Now start them yourself so you can see what they do. You need three terminals. In <b>terminal 1</b>, run <code>robot_state_publisher</code>. It reads your robot description and publishes a frame for every link:"],
          ["cmd", "cd ~/robot_practice", "Terminal 1 (Ubuntu)"],
          ["cmd", "ros2 run robot_state_publisher robot_state_publisher --ros-args -p robot_description:=\"$(xacro mybot.xacro)\"", "Terminal 1 (Ubuntu)"],
          ["p", "The <code>$(xacro ...)</code> part runs xacro first and hands the finished URDF to the node as a parameter. In <b>terminal 2</b>, start the node that supplies joint angles for the moving wheels (all zero, until a slider or program says otherwise):"],
          ["cmd", "ros2 run joint_state_publisher joint_state_publisher", "Terminal 2 (Ubuntu)"],
          ["note", "Without <code>joint_state_publisher</code>, <code>robot_state_publisher</code> can still publish the <b>fixed</b> frames (the head), but it has no angle for the wheel joints, so the wheel frames do not exist at all."],
          ["p", "In <b>terminal 3</b>, look at what is now being published:"],
          ["cmd", "ros2 topic list", "Terminal 3 (Ubuntu)"],
          ["out", "/joint_states\n/parameter_events\n/robot_description\n/rosout\n/tf\n/tf_static"],
          ["h", "Ask TF2 a question"],
          ["p", "<code>tf2_echo</code> answers &quot;where is frame B, measured from frame A?&quot;. Where is the head, relative to the base?"],
          ["cmd", "ros2 run tf2_ros tf2_echo base_link head", "Terminal 3 (Ubuntu)"],
          ["out", "At time 0.0\n- Translation: [0.100, 0.000, 0.120]\n- Rotation: in Quaternion (xyzw) [0.000, 0.000, 0.000, 1.000]\n- Rotation: in RPY (radian) [0.000, -0.000, 0.000]\n- Rotation: in RPY (degree) [0.000, -0.000, 0.000]\n- Matrix:\n  1.000  0.000  0.000  0.100\n  0.000  1.000  0.000  0.000\n  0.000  0.000  1.000  0.120\n  0.000  0.000  0.000  1.000"],
          ["p", "That is exactly the <code>origin xyz=&quot;0.1 0 0.12&quot;</code> you wrote in the URDF: 0.1 m forward, 0.12 m up, and no rotation. The rotation is shown three ways. A <b>quaternion</b> is four numbers that ROS uses internally, where <code>[0, 0, 0, 1]</code> means &quot;not rotated&quot;. <b>RPY</b> is roll, pitch and yaw, in radians and in degrees, which is easier for humans."],
          ["note", "You may see a line first that says <i>Waiting for transform ... frame does not exist</i>. That is normal: the tool started a moment before the first transform arrived. Press <code>Ctrl+C</code> to stop <code>tf2_echo</code>, because it keeps printing."],
          ["p", "Try the left wheel too:"],
          ["cmd", "ros2 run tf2_ros tf2_echo base_link left_wheel", "Terminal 3 (Ubuntu)"],
          ["out", "At time 1791285316.968771596\n- Translation: [-0.100, 0.120, -0.020]\n- Rotation: in Quaternion (xyzw) [0.000, 0.000, 0.000, 1.000]"],
          ["p", "The time is a big number rather than 0.0 because this frame is <b>moving</b> (it can spin), so it arrives on <code>/tf</code> over and over with fresh timestamps, whereas the head is static."],
          ["h", "Draw the whole tree"],
          ["cmd", "ros2 run tf2_tools view_frames", "Terminal 3 (Ubuntu)"],
          ["out", "[INFO] [view_frames]: Listening to tf data for 5.0 seconds...\n[INFO] [view_frames]: Generating graph in frames.pdf file...\n[INFO] [view_frames]: Result:tf2_msgs.srv.FrameGraph_Response(frame_yaml=\"left_wheel: \\n  parent: 'base_link'\\n  broadcaster: 'default_authority'\\n  rate: 10.200 ... (shortened)"],
          ["cmd", "ls frames_*", "Terminal 3 (Ubuntu)"],
          ["out", "frames_2026-10-06_14.15.23.gv\nframes_2026-10-06_14.15.23.pdf"],
          ["p", "The file names carry the date and time, so yours will differ. The <code>.pdf</code> is a diagram of the tree: <code>base_link</code> at the top with <code>head</code>, <code>left_wheel</code> and <code>right_wheel</code> hanging below it. To open it from Windows, paste this into the File Explorer address bar (replace <code>daniel</code> with your Linux user name):"],
          ["code", "\\\\wsl.localhost\\Ubuntu-22.04\\home\\daniel\\robot_practice", "File Explorer address bar"],
          ["h", "Add a frame yourself"],
          ["p", "Suppose you bolt a camera onto the robot, 0.2 m forward and 0.15 m up. You can announce a new fixed frame without touching the URDF:"],
          ["cmd", "ros2 run tf2_ros static_transform_publisher --x 0.2 --y 0 --z 0.15 --frame-id base_link --child-frame-id camera", "Terminal 3 (Ubuntu)"],
          ["p", "Leave that running, open <b>terminal 4</b> and ask:"],
          ["cmd", "ros2 run tf2_ros tf2_echo base_link camera", "Terminal 4 (Ubuntu)"],
          ["out", "At time 0.0\n- Translation: [0.200, 0.000, 0.150]\n- Rotation: in Quaternion (xyzw) [0.000, 0.000, 0.000, 1.000]"],
          ["p", "TF2 now knows about a <code>camera</code> frame. Anything that sees something in the camera frame can ask TF2 for its position in <code>base_link</code>, and the answer will be right."],
          ["note", "Later, in the navigation lesson, you will meet a longer chain: <code>map</code> to <code>odom</code> to <code>base_link</code>. It is the same idea: each link in the chain is a transform, and TF2 multiplies them for you."],
          ["warn", "Stop everything with <code>Ctrl+C</code> in each terminal when you finish. Leftover ROS nodes keep running in the background, use CPU, and make later <code>ros2 topic list</code> output confusing."],
          ["try", "Run <code>robot_state_publisher</code> and <code>joint_state_publisher</code>, then use <code>tf2_echo</code> to find where <code>right_wheel</code> is relative to <code>base_link</code>. It should match your URDF. Then run <code>view_frames</code> and open the PDF."],
          ["quiz", {
            q: "A camera is welded to your robot and never moves relative to it. Which topic carries that transform?",
            options: ["/tf_static", "/cmd_vel", "/joint_states", "/scan"],
            answer: 0,
            why: "Transforms that never change go on <code>/tf_static</code> and are sent once. Moving parts, such as wheels, publish on <code>/tf</code> continuously."
          }]
        ]
      },
      {
        id: "4.5", title: "Gazebo and the TurtleBot3", minutes: 35,
        blocks: [
          ["p", "RViz <i>shows</i> a robot. <b>Gazebo</b> <i>simulates</i> one: it adds gravity, wheels that grip the floor, collisions, and fake sensors that produce data like real hardware. You will use it with the <b>TurtleBot3 Burger</b>, a small, popular, two-wheeled robot with a 360-degree lidar. The simulated robot has the same topics as the real one, so what you learn transfers directly."],
          ["note", "Gazebo shows a banner saying this version reaches end-of-life in January 2025. That is expected. ROS 2 Humble works with this version (Gazebo 11, called &quot;Classic&quot;), and the banner can be ignored."],
          ["h", "One-time setup"],
          ["p", "First, tell the TurtleBot3 packages which model you want. Add it to <code>~/.bashrc</code> <b>once</b>, then open a new terminal:"],
          ["cmd", "echo \"export TURTLEBOT3_MODEL=burger\" >> ~/.bashrc"],
          ["p", "You should already have <code>LIBGL_ALWAYS_SOFTWARE=1</code> from lesson 4.2. Check it:"],
          ["cmd", "echo $LIBGL_ALWAYS_SOFTWARE $TURTLEBOT3_MODEL"],
          ["out", "1 burger"],
          ["p", "Second, Gazebo needs two basic models, the <b>ground plane</b> and the <b>sun</b>. It normally downloads them the first time, but that download can stall and leave you with a black window. Download them yourself, once:"],
          ["cmd", "mkdir -p ~/.gazebo/models"],
          ["cmd", "cd ~/.gazebo/models"],
          ["cmd", "curl -sL -o /tmp/ground_plane.tgz http://models.gazebosim.org/ground_plane/model.tar.gz && tar xzf /tmp/ground_plane.tgz"],
          ["cmd", "curl -sL -o /tmp/sun.tgz http://models.gazebosim.org/sun/model.tar.gz && tar xzf /tmp/sun.tgz"],
          ["cmd", "ls ~/.gazebo/models"],
          ["out", "ground_plane  sun"],
          ["h", "Launch the simulation"],
          ["cmd", "ros2 launch turtlebot3_gazebo empty_world.launch.py", "Terminal 1 (Ubuntu)"],
          ["p", "Be patient: the first start can take a minute or more. When it works you will see this line in the terminal, and a <b>Gazebo window</b> opens with a flat grey floor and a small robot with <b>blue rays</b> fanning out from it. Those rays are the lidar beams."],
          ["out", "[spawn_entity.py-4] [INFO] ... [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [burger]"],
          ["p", "Rotate the view with the left mouse button, slide it with the middle button and zoom with the scroll wheel, just like RViz."],
          ["warn", "Software rendering is slow and Gazebo is heavy. Close other big programs (browsers with many tabs, Docker, other simulators) before launching. If the picture looks jerky, that is normal, and the robot is still being simulated correctly."],
          ["warn", "<b>Always close Gazebo properly.</b> Press <code>Ctrl+C</code> in terminal 1 and wait. Then check that nothing is left behind: <code>pgrep gzserver</code> should print <b>nothing</b>. If it prints a number, run <code>killall -9 gzserver gzclient</code>. A leftover server keeps Gazebo&apos;s network port busy, and the <i>next</i> launch silently hangs with <code>Service /spawn_entity unavailable</code> in the log."],
          ["h", "What is the robot publishing?"],
          ["p", "Leave Gazebo running and open <b>terminal 2</b>:"],
          ["cmd", "ros2 topic list", "Terminal 2 (Ubuntu)"],
          ["out", "/clock\n/cmd_vel\n/imu\n/joint_states\n/odom\n/parameter_events\n/performance_metrics\n/robot_description\n/rosout\n/scan\n/tf\n/tf_static"],
          ["cmd", "ros2 topic list -t | grep -E \"cmd_vel|odom|scan|imu\"", "Terminal 2 (Ubuntu)"],
          ["out", "/cmd_vel [geometry_msgs/msg/Twist]\n/imu [sensor_msgs/msg/Imu]\n/odom [nav_msgs/msg/Odometry]\n/scan [sensor_msgs/msg/LaserScan]"],
          ["ul", [
            "<code>/cmd_vel</code> (<code>Twist</code>): the robot <b>listens</b> here. You publish a velocity and it drives. It is the same message type you used to move the turtle in lesson 2.6.",
            "<code>/odom</code> (<code>Odometry</code>): the robot&apos;s estimate of its own position, from counting wheel turns.",
            "<code>/scan</code> (<code>LaserScan</code>): the lidar. Distances to the nearest obstacle in every direction.",
            "<code>/imu</code> (<code>Imu</code>): a motion sensor, for tilt and turning speed."
          ]],
          ["cmd", "ros2 node list", "Terminal 2 (Ubuntu)"],
          ["out", "/gazebo\n/robot_state_publisher\n/turtlebot3_diff_drive\n/turtlebot3_imu\n/turtlebot3_joint_state\n/turtlebot3_laserscan"],
          ["p", "Each sensor and the wheel drive is its own node, created by plugins inside the simulator. The robot is made of the same pieces you have been learning."],
          ["h", "Drive it"],
          ["p", "Read where the robot is now:"],
          ["cmd", "ros2 topic echo --once --field pose.pose.position /odom", "Terminal 2 (Ubuntu)"],
          ["out", "x: 5.810263146661501e-05\ny: -9.940400327789326e-07\nz: 0.008526358832711942\n---"],
          ["p", "It starts essentially at (0, 0). The tiny numbers are simulation noise. Now publish a forward speed of 0.2 metres per second, 5 times a second, 12 times in a row:"],
          ["cmd", "ros2 topic pub --times 12 -r 5 /cmd_vel geometry_msgs/msg/Twist \"{linear: {x: 0.2}, angular: {z: 0.0}}\"", "Terminal 2 (Ubuntu)"],
          ["p", "In the Gazebo window the robot rolls forward. Stop it and read the position again:"],
          ["cmd", "ros2 topic pub --once /cmd_vel geometry_msgs/msg/Twist \"{}\"", "Terminal 2 (Ubuntu)"],
          ["cmd", "ros2 topic echo --once --field pose.pose.position /odom", "Terminal 2 (Ubuntu)"],
          ["out", "x: 0.6800609128902806\ny: -1.076680794312546e-06\nz: 0.008511148177147793\n---"],
          ["p", "<code>x</code> grew to about 0.68 m and <code>y</code> stayed near zero, so it drove straight. Your exact number will differ a little, because the simulation does not run in perfect real time. The empty message <code>{}</code> is a Twist of all zeros, which means &quot;stop&quot;."],
          ["warn", "Always send a zero Twist when you finish driving. A robot does what its last command said, and on a real robot forgetting to stop it can be expensive."],
          ["p", "To drive by hand with the keyboard, run this in a terminal and press its keys while that terminal is selected (it prints its own help list when it starts). Press <code>Ctrl+C</code> to quit:"],
          ["cmd", "ros2 run teleop_twist_keyboard teleop_twist_keyboard", "Terminal 2 (Ubuntu)"],
          ["h", "Read the lidar"],
          ["p", "A <code>LaserScan</code> describes a ring of distance measurements. Ask for its settings:"],
          ["cmd", "ros2 topic echo --once --field range_min /scan", "Terminal 2 (Ubuntu)"],
          ["out", "0.11999999731779099"],
          ["cmd", "ros2 topic echo --once --field range_max /scan", "Terminal 2 (Ubuntu)"],
          ["out", "3.5"],
          ["cmd", "ros2 topic echo --once --field angle_increment /scan", "Terminal 2 (Ubuntu)"],
          ["out", "0.01749303564429283"],
          ["p", "So the lidar sees from 0.12 m out to 3.5 m. The beams are 0.0175 radians (one degree) apart, and a full turn is about 6.28 radians, so one scan holds <b>360 distances</b> in a list called <code>ranges</code>. Beam 0 points straight ahead, and the rest go counter-clockwise. A reading of <code>inf</code> means &quot;nothing within 3.5 m in that direction&quot;. In the empty world almost everything is <code>inf</code>."],
          ["note", "Do not echo <code>ranges</code> directly. ROS shortens long lists to <code>'...'</code> in the terminal. In the next lesson you will read the whole list with Python."],
          ["cmd", "ros2 topic hz /odom", "Terminal 2 (Ubuntu)"],
          ["out", "average rate: 29.297\n\tmin: 0.032s max: 0.037s std dev: 0.00108s window: 31"],
          ["p", "Odometry arrives about 30 times a second. The scan arrives much slower, around 5 times a second, which is normal for a lidar. Press <code>Ctrl+C</code> to stop <code>topic hz</code>."],
          ["h", "A world with obstacles"],
          ["p", "Close the empty world properly (see the warning above), then launch the world with nine pillars. This is the same layout that the navigation lesson will use:"],
          ["cmd", "ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py", "Terminal 1 (Ubuntu)"],
          ["p", "Look at the Gazebo window: the blue lidar rays now stop at the pillars instead of flying off into nothing. Almost all of the 360 beams now hit something, and the nearest object is about half a metre away."],
          ["try", "Launch the empty world, drive the robot forward with the <code>/cmd_vel</code> command, stop it, and check that <code>/odom</code> changed. Then close Gazebo with <code>Ctrl+C</code> and confirm <code>pgrep gzserver</code> prints nothing."],
          ["quiz", {
            q: "Which topic do you publish a <code>Twist</code> to, in order to drive the simulated TurtleBot3?",
            options: ["/scan", "/odom", "/cmd_vel", "/imu"],
            answer: 2,
            why: "<code>/cmd_vel</code> (command velocity) is the robot&apos;s input. <code>/scan</code>, <code>/odom</code> and <code>/imu</code> are outputs that it publishes."
          }]
        ]
      }
    ]
  });
})();
